# Site settings
title: TCDL
header-img: img/home-bg.jpg
description: "Tecnicas de Construcción de Lenguajes"
baseurl: ""
url: "http://tcdl-utn.github.io/"
github_username: "tcdl-utn"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: blog/page:num
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
